version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: ./typescript/simple-mercari-web/dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./typescript/simple-mercari-web:/app/simple-mercari-web

  backend:
    build:
      context: .
      dockerfile: ./go/dockerfile
    ports:
      - "9000:9000"