version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: ./typescript/simple-mercari-web/dockerfile
    ports:
      - "3000:3000"
    environment:
      API_URL: http://localhost:9000

  backend:
    build:
      context: .
      dockerfile: ./go/dockerfile
    ports:
      - "9000:9000"
    environment:
      FRONT_URL: http://localhost:3000